--add compatibility with the old nodes of king arthurs land
minetest.register_alias("darkage:stair_stonebrick", "darkage:stair_basalt_cobble")
minetest.register_alias("darkage:stair_stonebrick_inverted", "darkage:stair_basalt_cobble_inverted")
minetest.register_alias("darkage:stair_stonebrick_wall", "darkage:stair_basalt_cobble_wall")
minetest.register_alias("darkage:slab_stonebrick_inverted", "darkage:slab_basalt_cobble_inverted")
minetest.register_alias("darkage:slab_stonebrick_wall", "darkage:slab_basalt_cobble_wall")
minetest.register_alias("darkage:slab_stonebrick", "darkage:slab_basalt_cobble")
minetest.register_alias("darkage:panel_stonebrick_vertical", "darkage:panel_basalt_cobble_vertical")
minetest.register_alias("darkage:panel_stonebrick_bottom", "darkage:panel_basalt_cobble_bottom")
minetest.register_alias("darkage:panel_stonebrick_top", "darkage:panel_basalt_cobble_top")
